name: motion-alarm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Test
        run: |
          pip install -r requirements-test.txt --extra-index-url https://packages.beerfie.com/pypi
          pytest -v
          find . -type f -name "*.py" | xargs pylint 
